# version: "3"
# services:

#   app:
#     image: mcr.microsoft.com/dotnet/sdk:5.0
#     command: bash -c "dotnet restore && dotnet build && dotnet run  --urls http://+:5000"
#     working_dir: /app
#     volumes:
#       - ./app:/app
#     ports:
#       - "5000:5000"
#     logging:
#           driver: loki
#           options:
#             loki-url: https://44364:eyJrIjoiMjc1ZDQ1NzUxNDNkOTQ0NmEzMTllYzEyOWQxYjFhMmY2ZDk5NDAzMSIsIm4iOiJMb2tpIiwiaWQiOjQ4NzQ2MX0=@logs-prod-us-central1.grafana.net/api/prom/push
#   grafana-agent:
#     image: grafana/agent:latest
#     command: "-config.file=/etc/agent-config.yaml"
#     # ports:
#     #   - "30001:3000"
#     volumes:
#       - ./agent-config.yaml:/etc/agent-config.yaml
#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     ports:
#       - 9090:9090
#     volumes:
#       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  # elasticsearch:
  #   image: elasticsearch:7.9.1
  #   environment:
  #     - http.host=0.0.0.0
  #     - discovery.type=single-node
  #     - script.allowed_types=inline
  #     - thread_pool.search.queue_size=100000
  #     - thread_pool.write.queue_size=10000
  #   volumes:
  #     - /path/to/data:/usr/share/elasticsearch/data
  # cortex:
  #   image: thehiveproject/cortex:3.1.1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "0.0.0.0:9001:9001"

